### PR TITLE
Dart 2.12 migrated with Null-Safety.

### PR DESCRIPTION
**Pull request by alex-melnyk**

### CODE REVIEW

**Comment by alex-melnyk** [comment]
@sanathe06 Please merge this PR and publish it.

**Comment by sanathe06** [comment]
@alex-melnyk thank you very much, I will publish a new version as soon as possible.

**Comment by alex-melnyk** [comment]
Great, thank you for quick response

**Comment by alex-melnyk** [comment]
Also, please notice that you can setup an action to publish your plugin by adding release tag it will simplify this process.

Take a look at example in my plugin:
https://github.com/alex-melnyk/flutter_advanced_drawer/actions/runs/808299137/workflow

**Comment by sanathe06** [comment]
Thank you very much, I will have a look.

*Best Regards,*



*Sanath Nandasiri*

*Head of Mobile Practice/Tech Lead*

*Tiqri Corporation (Pvt) Ltd*

**Pull request merged**
